steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, '-t', 'gcr.io/$PROJECT_ID/_$SERVICE_NAME:$SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/_$SERVICE_NAME:$SHA']
  - name: gcr.io/cloud-builders/gcloud
    args: ['run', 'deploy','build-001-cloud-build', '--project', '$PROJECT_ID', '--image', 'gcr.io/$PROJECT_ID/_$SERVICE_NAME:$SHA', --allow-unauthenticated']

